packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@depot/cli': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
minimumReleaseAge: 0
