import './globals.css'
import { cn } from '~/lib/utils'
import type { Metadata } from 'next'
import { montserrat, nunito, inter } from '~/fonts'
import Provider from './provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'scroll-smooth antialiased',
          montserrat.variable,
          nunito.variable,
          inter.variable
        )}
      >
        <Provider>
          <main className="font-nunito mx-auto min-h-screen w-full max-w-[1500px]">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
