import './globals.css'
import { auth } from '~/auth'
import { cn } from '~/lib/utils'
import Provider from './provider'
import type { Metadata } from 'next'
import { montserrat, nunito, inter } from '~/fonts'
import { SessionProvider } from 'next-auth/react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'scroll-smooth antialiased',
          montserrat.variable,
          nunito.variable,
          inter.variable
        )}
      >
        <SessionProvider session={session}>
          <Provider>
            <main className="font-nunito mx-auto min-h-screen w-full max-w-[1500px]">
              {children}
            </main>
          </Provider>
        </SessionProvider>
      </body>
    </html>
  )
}
